In [152]:
import pandas as pd 
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt 
from sklearn.utils import shuffle
%matplotlib inline

In [186]:
np.random.seed(42)
x = np.random.randint(10, 15, size=30)
y = np.random.randint(11, 15, size=30)
z = np.random.randint(10, 20, size=30)
w = np.random.randint(13, 18, size=30)

In [187]:
data = (x,y,z,w)

In [188]:
data = [np.array(datum, dtype=float) for datum in data]
data

[array([13., 14., 12., 14., 14., 11., 12., 12., 12., 14., 13., 12., 14.,
        11., 13., 11., 13., 14., 10., 13., 11., 14., 13., 10., 10., 12.,
        12., 11., 13., 13.]),
 array([14., 13., 12., 12., 13., 12., 13., 14., 13., 14., 14., 11., 13.,
        11., 13., 13., 11., 11., 13., 12., 14., 11., 14., 12., 12., 12.,
        11., 12., 11., 12.]),
 array([13., 16., 17., 12., 10., 13., 11., 17., 13., 11., 15., 15., 19.,
        13., 15., 11., 19., 11., 19., 13., 17., 16., 18., 17., 14., 11.,
        14., 17., 19., 18.]),
 array([16., 16., 16., 17., 13., 17., 17., 13., 13., 13., 13., 16., 15.,
        15., 13., 15., 15., 13., 15., 17., 14., 14., 13., 16., 13., 16.,
        14., 13., 17., 15.])]

In [189]:
elemszamok = [data[i].shape[0] for i in range(len(data))]
elemszamok

[30, 30, 30, 30]

In [190]:
csoportszam = len(elemszamok)
csoportszam

4

In [191]:
pool = np.concatenate(data, axis=0)
pool

array([13., 14., 12., 14., 14., 11., 12., 12., 12., 14., 13., 12., 14.,
       11., 13., 11., 13., 14., 10., 13., 11., 14., 13., 10., 10., 12.,
       12., 11., 13., 13., 14., 13., 12., 12., 13., 12., 13., 14., 13.,
       14., 14., 11., 13., 11., 13., 13., 11., 11., 13., 12., 14., 11.,
       14., 12., 12., 12., 11., 12., 11., 12., 13., 16., 17., 12., 10.,
       13., 11., 17., 13., 11., 15., 15., 19., 13., 15., 11., 19., 11.,
       19., 13., 17., 16., 18., 17., 14., 11., 14., 17., 19., 18., 16.,
       16., 16., 17., 13., 17., 17., 13., 13., 13., 13., 16., 15., 15.,
       13., 15., 15., 13., 15., 17., 14., 14., 13., 16., 13., 16., 14.,
       13., 17., 15.])

In [192]:
pool = shuffle(pool)
pool

array([10., 12., 14., 12., 15., 12., 11., 17., 14., 13., 13., 14., 16.,
       12., 18., 19., 14., 11., 11., 11., 12., 13., 13., 14., 12., 16.,
       13., 13., 17., 14., 14., 14., 12., 13., 10., 13., 17., 12., 17.,
       16., 11., 14., 14., 13., 12., 17., 14., 13., 12., 13., 13., 13.,
       14., 14., 12., 14., 12., 16., 10., 15., 16., 17., 12., 13., 13.,
       13., 11., 17., 15., 17., 15., 19., 13., 13., 15., 13., 17., 11.,
       11., 16., 13., 16., 13., 11., 11., 15., 13., 14., 12., 13., 13.,
       13., 13., 14., 11., 17., 14., 19., 11., 15., 13., 19., 12., 12.,
       15., 11., 18., 14., 13., 12., 11., 11., 13., 13., 10., 13., 16.,
       11., 15., 11.])

In [195]:
# list of numpy array

In [193]:
args = [resample(pool, size=elemszamok[i]) for i in range(csoportszam)]

In [196]:
args

[array([14., 13., 11., 16., 13., 16., 14., 17., 19., 10., 11., 16., 17.,
        11., 13., 18., 13., 13., 13., 19., 12., 11., 18., 12., 13., 16.,
        11., 13., 12., 13.]),
 array([13., 19., 11., 10., 12., 12., 11., 16., 11., 13., 13., 14., 12.,
        17., 11., 12., 15., 14., 13., 19., 15., 13., 13., 14., 15., 16.,
        14., 16., 11., 12.]),
 array([16., 13., 12., 12., 12., 16., 11., 11., 11., 11., 13., 13., 14.,
        14., 13., 19., 17., 12., 11., 13., 14., 13., 11., 12., 14., 17.,
        14., 15., 19., 13.]),
 array([11., 16., 14., 13., 12., 13., 15., 15., 13., 13., 12., 17., 17.,
        13., 13., 13., 12., 11., 12., 10., 11., 13., 13., 12., 13., 11.,
        14., 19., 16., 16.])]

In [140]:
def resample(x, size, replace=False):
    return np.random.choice(x, size=size, replace=replace)

In [199]:
x,y = args[:2]

In [200]:
x

array([14., 13., 11., 16., 13., 16., 14., 17., 19., 10., 11., 16., 17.,
       11., 13., 18., 13., 13., 13., 19., 12., 11., 18., 12., 13., 16.,
       11., 13., 12., 13.])

In [202]:
len(data)

4

In [203]:
x

array([14., 13., 11., 16., 13., 16., 14., 17., 19., 10., 11., 16., 17.,
       11., 13., 18., 13., 13., 13., 19., 12., 11., 18., 12., 13., 16.,
       11., 13., 12., 13.])

In [204]:
y

array([13., 19., 11., 10., 12., 12., 11., 16., 11., 13., 13., 14., 12.,
       17., 11., 12., 15., 14., 13., 19., 15., 13., 13., 14., 15., 16.,
       14., 16., 11., 12.])

In [213]:
np.corrcoef(x,y)

array([[1.        , 0.01216728],
       [0.01216728, 1.        ]])

In [214]:
np.correlate(y,x)

array([5673.])

In [215]:
pd.Series(x).corr(pd.Series(y))

0.012167279271462016